apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MYSQL_DATABASE: weatherapp
  MYSQL_USER: admin
  DB_HOST: alpha-db-service
  REDIS_USER: redis
  AUTH_HOST: alpha-auth-service 
  AUTH_PORT: "8080"
  WEATHER_PORT: "5000"
  WEATHER_HOST: alpha-weather-service