# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: app-ingress-external-dns
#   labels:
#     app: app-ingress
#   annotations:
#     kubernetes.io/ingress.class: "alb" 
#     alb.ingress.kubernetes.io/load-balancer-name: external-dns-ingress
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
#     # Heath check settings
#     # alb.ingress.kubernetes.io/healthcheck-port: '80'
#     alb.ingress.kubernetes.io/healthcheck-port: traffic-port  
#     alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
#     alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
#     alb.ingress.kubernetes.io/success-codes: '200'
#     alb.ingress.kubernetes.io/healthy-threshold-count: '2'
#     alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
#     # SSH settings
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
#     # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:788210522308:certificate/a6e6e5cb-6c76-4fa6-82de-f07673094ccd
#     # SSL Redirect Setting (http to https) all http will be redirected to https
#     alb.ingress.kubernetes.io/ssl-redirect: '443'
#     # External dns settings
#     external-dns.alpha.kubernetes.io/hostname: ui.devopssimplelearning.com, app.devopssimplelearning.com
# spec:
#   defaultBackend:
#     service:
#       name: alpha-ui-service
#       port:
#         number: 3000
#   rules: 
#     - host: weather.devopssimplelearning.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: alpha-weather-service
#                 port: 
#                   number: 5000
#     - host: auth.devopssimplelearning.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: alpha-auth-service
#                 port: 
#                   number: 8080